name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install git-lfs && git lfs install

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install && bun add faiss-node --allow-build=faiss-node

      - name: Generate static pages
        run: bun run build
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SITE_KEY }}
      - name: Copy header & redirect specific files
        run: cp _headers dist/_headers & cp _redirects dist/_redirects
      - name: Publish CF website
        run: bunx wrangler@latest pages deploy dist --project-name codepushgo-website --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
