name: Sync SEObot Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install git-lfs && git lfs install

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install && bun add faiss-node --allow-build=faiss-node
        
      - name: Sync blog posts
        env:
          SEOBOT_API_KEY: ${{ secrets.SEOBOT_API_KEY }}
        run: bun .github/scripts/sync-blog.js
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/content/blog/en/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: sync blog posts from SEObot"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 
